export const DELETE_TODO = "DELETE_TODO";
export const CREATE_TODO = "CREATE_TODO";
export const FETCH_TODOS = "FETCH_TODOS";
export const DELETE_COMPLETED = "DELETE_COMPLETED";
export const CREATE_COMPLETED = "CREATE_COMPLETED";
export const FETCH_COMPLETED = "FETCH_COMPLETED";
export const UPDATE_STATE = "UPDATE_STATE";
export const CLEAR_STATE = "CLEAR_STATE";
